# Generated by Django 5.0.3 on 2024-03-17 22:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="text",
            field=models.CharField(max_length=1000000000, unique=True),
        ),
    ]
