# Generated by Django 5.0.3 on 2024-03-24 18:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_post_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarkdownContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("markdown_content", models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name="Post",
        ),
    ]
